### ISSUE TITLE
How to test save-as-pdf?

### ISSUE THREAD

**Issue by zerowind168** [ArcticLampyrid/ippper.rs#50]
Could you please add something about what platform have you test. Both for client and server.

**Comment by ArcticLampyrid** [comment]
What problem did you meet?
遇到了什么问题吗？

**Comment by ArcticLampyrid** [comment]
Server:
```sh
cargo run --example save_as_pdf
```
Tested client:
- Win10 IPP Client (via `Add a printer using TCP/IP address or hostname`)
- Android Printer Service (tested on Huawei)

**Comment by zerowind168** [comment]
![image](https://user-images.githubusercontent.com/6487289/181149111-07b12097-c517-40e1-9c3b-698a04599457.png)
![image](https://user-images.githubusercontent.com/6487289/181149273-2b8e425c-39e2-45fe-a9fc-35bf974a5abf.png)
![image](https://user-images.githubusercontent.com/6487289/181149389-91b61375-0df5-4b72-9ff7-6fc67cfe7dce.png)
![image](https://user-images.githubusercontent.com/6487289/181149487-6e11cb93-7873-4fd3-9aa5-119306e1b660.png)

**Comment by zerowind168** [comment]
![image](https://user-images.githubusercontent.com/6487289/181149809-670efea2-86d6-4071-82dc-9199486254fb.png)

**Comment by zerowind168** [comment]
不知道上面哪个步骤不正确

**Comment by zerowind168** [comment]
你的代码我是在WIN10本机上运行。添加打印机也是在本机。
![image](https://user-images.githubusercontent.com/6487289/181150710-3488de93-6f26-4def-8790-22fbfe3a6634.png)

**Comment by ArcticLampyrid** [comment]
![image](https://user-images.githubusercontent.com/9017609/181150958-4e9dfa05-5c8d-4f89-aab7-1a5fd352ffd0.png)
需要选择 `IPP 设备`（新版Windows才有）

**Comment by ArcticLampyrid** [comment]
主机名那里可以填写 `http://127.0.0.1:631/` （虽然提示的是 hostname or IP）

**Comment by zerowind168** [comment]
多谢！换了一台家庭版的WIN10，有IPP设备，测试没有问题。之前用的企业版WIN10没有IPP这个选项。
